import numpy as np
import pandas as pd
import pickle
from keras.layers import Input, Dense, Flatten, Activation
from keras.models import model_from_json, Sequential
import json
import warnings

warnings.filterwarnings("ignore")

Training_dir = "Training.csv"

Df = pd.read_csv(Training_dir)

Cols = Df.columns[:-1]

Symptoms = list(Cols)

# print(Symptoms)


def BringOut():
    with open("file.txt") as f:
        data = f.read()
    data = data.split("[")[1].split("]")[0]
    data = list(map(lambda x: eval(x), data.split(",")))
    return data


'''
with open("file.txt" , "r") as f :
  symp = f.read()
'''

symp = BringOut()

#symp = input(" Enter Symptoms with ',' in between ")

#symp = symp.split(",")

raw = np.zeros(len(Symptoms))

for i in range(len(symp)):
    for j in range(len(Symptoms)):
        if symp[i] == Symptoms[j]:
            raw[j] = 1

raw = np.array(raw)

raw = raw.reshape(1, 132)

json_file = open('model.json', 'r')
loaded_model_json = json_file.read()
json_file.close()
loaded_model = model_from_json(loaded_model_json)

loaded_model.load_weights("model.h5")

loaded_model.compile(
    loss='categorical_crossentropy',
    optimizer='adagrad',
    metrics=['accuracy']
)

predictions = loaded_model.predict(raw)

maxi = np.argmax(predictions)


def LoadEncoderObject(path):
    pkl_file = open(path, 'rb')
    Le = pickle.load(pkl_file)
    pkl_file.close()
    return Le


Encoder = LoadEncoderObject("Encoder.pkl")

val = Encoder.inverse_transform([maxi])

# Val contains the disease
val = val[0]

print(val)

diseases = {'Dengue': ["Dengue is a mosquito-borne viral infection causing a severe flu-like illness and sometimes causing a potentially lethal complication called severe dengue.", " soak the leaves in water and then drink it or you can get methi powder and mix it with water and have it. Goldenseal Goldenseal is a herb whose dried root is used to make medicine. It has the ability to clear up the symptoms of dengue fever very quickly and eliminate the virus from the body. ", " patients are advised to consume high protein diet to get required supply of vitamins, minerals, proteins and fats. "],
            'Peptic ulcer diseae': ["A sore that develops on the lining of the oesophagus, stomach or small intestine. ", "cabbage juice, licorice, honey, garlic, turmeric and chilli peppers. ", " Eat a diet rich in fiber, especially from fruits and vegetables.Avoid foods that are fried or high in fat, also avoid alcohol, Quit smoking, Cut down on caffeine and spicy foods."],
            'Heart attack': ["During a heart attack, the blood supply that normally nourishes the heart with oxygen is cut off and the heart muscle begins to die. Heart attacks — also called myocardial infarctions are very common in the United States. In fact, it’s estimated that one happens every 40 seconds.Some people who are having a heart attack have warning signs, while others show no signs. Some symptoms that many people report are:chest pain , upper body pain , sweating , nausea , fatigue , trouble breathing .", "Angioplasty (An angioplasty opens the blocked artery by using a balloon or by removing the plaque buildup) , Stent( A stent is a wire mesh tube that’s inserted into the artery to keep it open after angioplasty ) , Heart bypass surgery , Heart valve surgery , Pacemaker , Heart transplant. ", " Vegetables and fruits are also low in calories and rich in dietary fiber. Vegetables and fruits, like other plants or plant-based foods, contain substances that may help prevent cardiovascular disease. Eating more fruits and vegetables may help you cut back on higher calorie foods, such as meat, cheese and snack foods"],
            'Hepatitis D': ["  A serious liver disease caused by infection with the hepatitis D virus. ", " You may be given large doses of a medication called interferon for up to 12 months. ", "Avoid the following: Saturated fats found in butter, sour cream, and other high-fat dairy foods, fatty cuts of meat, and fried foods."],
            'Fungal infection': ["Any disease caused by a fungus. ", "  Garlic is often used to treat infection. Although there are no studies that examine the effects of garlic on ringworm, it has proven effective for other types of fungi,including Candida, Torulopsis, Trichophyton, and Cryptococcus ", " Plain yogurt.The good bacteria in plain yogurt helps fight yeast and yogurt can be used both internally and externally. Garlic, Apple-cider Vinegar, Oil of Oregano."],
            'Impetigo': ["A highly contagious skin infection that causes red sores on the face. ", " Treatment consists of penicillins . Antibiotics shorten the infection and can help prevent spread to others. Medications\n Penicillin antibiotic and Antibiotics . Specialists \n Paediatrician, Primary Care Provider (PCP), and Dermatologist ", "A diet rich in organic fruits, vegetables, and whole grains and low in animal-based proteins can fortify your body’s natural defenses and healing system.Eliminate polyunsaturated vegetable oils, margarine, vegetable shortening, all partially hydrogenated oils, and all foods (such as deep-fried foods) that might contain trans-fatty acids. Use extra-virgin olive oil as your principal fat.Increase intake of omega-3 fatty acids.Eat ginger and turmeric regularly for their anti-inflammatory effects."],
            'AIDS': ["HIV causes AIDS and interferes with the body's ability to fight infections.", "Treatment consists of HIV antivirals . No cure exists for AIDS, but strict adherence to antiretroviral regimens (ARVs) can dramatically slow the disease's progress as well as prevent secondary infections and complications. Medications HIV antiviral Specialists Infectious Disease Doctor, Clinical Psychologist, and Primary Care Provider (PCP)", "Eating a diet high in vegetables, fruits, whole grains, and legumes. Choosing lean, low-fat sources of protein. Limiting sweets, soft drinks, and foods with added sugar. Including proteins, carbohydrates, and a little good fat in all meals and snacks"],
            'Urinary tract infection': ["An infection in any part of the urinary system, the kidneys, bladder or urethra.", " Drinking unsweetened cranberry juice is one of the most well-known natural remedies for urinary tract infections. Cranberries work by preventing bacteria from adhering to the urinary tract, thus preventing infection ", "Cranberry juice, lots of water, Good quality probiotics and fermented foods.avoid: sugar, caffeine, spicy food, alcohol."],
            '(vertigo) Paroymsal  Positional Vertigo': [" Vertigo is a symptom where a person feels as if they or the objects around them are moving when they are not. Often it feels like a spinning or swaying movement. This may be associated with nausea, vomiting, sweating, or difficulties walking. It is typically worse when the head is moved.[2] Vertigo is the most common type of dizziness.", " A series of simple head movements (known as the Epley manoeuvre) is used to treat BPPV. Medicines, such as prochlorperazine and some antihistamines, can help in the early stages or most cases of vertigo.", "High salt in the diet interferes with the internal homeostasis of the vestibular system. Patients with Meniere's disease and vestibular migraine are asked to limit their salt intake. Food rich in sodium like soy sauce, chips, popcorn, cheese, pickles, papad and canned foods are to be avoided "],
            'Migraine': ["A headache of varying intensity, often accompanied by nausea and sensitivity to light and sound.", " Treatment consists of pain medications -> Preventive and pain-relieving medication can help manage migraine headaches.Self-care -> Avoid migraine triggers, Stress management, Improved sleep habits, and Diet modification , Medications -> Antipsychotic, Analgesic, Nonsteroidal anti-Inflammatory drug, Stimulant, Nerve pain medication, Triptan, Neurotoxin, and Dietary supplement , Therapies ,Progressive muscle relaxation and Acupuncture ", "Migraine Dietary Triggers. Migraine is a very common problem. ... Commonly reported migraine triggers include alcohol (especially red wine and beer), chocolate, aged cheese, cured meats, smoked fish, yeast extract, food preservatives that contain nitrates and nitrites, artificial sweeteners, and monosodium glutamate (MSG)."],
            'Alcoholic hepatitis': ["Liver inflammation caused by drinking too much alcohol. ", " Treatment involves hydration, nutritional care and stopping alcohol use.Steroid drugs can help reduce liver inflammation. ", " High Nutritional value food. "],
            'Diabetes': [" Diabetes is a condition that results from lack of the hormone insulin in a person's blood, or when the body has a problem using the insulin it produces (insulin resistance). There is another disease with a similar name, diabetes insipidus, however they are not related. When people say diabetes, they usually mean diabetes mellitus. People with diabetes mellitus are called diabetics.Glucose level in the blood is controlled by several hormones. Hormones are chemicals in the body that send messages from cells to other cells. Insulin is a hormone made by the pancreas. When you eat, the pancreas makes insulin to send a message to other cells in the body. This insulin tells the cells to take up glucose from the blood. The glucose is used by cells for energy. Extra glucose that is not needed right away is stored in some cells as glycogen. When you are not eating, cells break down the stored glycogen into glucose to use as energy.", " 1. Bitter Gourd (Karela)Drink one small glass of this juice on empty stomach every morning. \n 2. FENUGREEK \n Fenugreek is a commonly used herb in Indian kitchen with great many benefits.  It is helps to control diabetes, improve glucose tolerance, lower blood sugar levels and stimulate the secretion of glucose-dependent insulin. \n How to use: Soak 2 tbsp of fenugreek seeds in water overnight and drink that water along with the seeds in the morning in an empty stomach daily to bring down your glucose level.Consume fenugreek seed powder with hot or cold water or milk daily.", "Salmon, sardines, herring, anchovies and mackerel are great sources of the omega-3 fatty acids DHA and EPA, which have major benefits for heart health."],
            'Hepatitis B': ["A severe form of viral hepatitis transmitted in infected blood, causing fever, debility, and jaundice.", " Chronic hepatitis B is not curable, but it is treatable. The goal of therapy is to reduce the risk of complications. ", " Avoid the following: Saturated fats found in butter, sour cream, and other  high-fat dairy foods, fatty cuts of meat, and fried foods. "],
            'Dimorphic hemmorhoids(piles)': [" Swollen and inflamed veins in the rectum and anus that cause discomfort and bleeding. ", " Soak regularly in a warm bath or sitz bath,Keep the anal area clean and do not use dry toilet paper. Take oral pain relievers. ", " Great food sources of fiber include: Legumes, such as split peas, lentils, black beans, lima beans, and baked beans. Whole grains, such as barley, bran flakes, oatmeal, and brown rice. Vegetables, such as artichoke, green peas, broccoli, and Brussels sprouts."],
            'Psoriasis': [" A condition in which skin cells build up and form scales and itchy, dry patches.", " Treatment consists of skin care , Treatment aims to remove scales and stop skin cells from growing so quickly. Topical ointments, light therapy and medication can offer relief.Medical procedure Photodynamic therapy Medications Steroid, Vitamin A derivative, Anti-Inflammatory, Immunosuppressive drug, and Vitamin Self-care Stress management, Petroleum jelly, Coal tar extract, Light therapy, Ultraviolet light therapy, Moisturizer, and Urea Specialists Rheumatologist, Primary Care Provider (PCP), and Dermatologist", "Fish and seafood. Omega-3 fatty acids—abundant in fatty fish such as salmon, mackerel, sardines, and albacore tuna—are the foundation of a heart-healthy diet. Fish oils are thought to reduce inflammation and help the immune system, which is overactive in people with psoriasis. "],
            'Gastroenteritis': [" An intestinal infection marked by diarrhoea, cramps, nausea, vomiting and fever. ", " Treatment consists of fluids \n Avoiding contaminated food and water and washing hands can often help prevent infection. Rest and rehydration are the mainstays of treatment. \n Supportive care : Fluid replacement, Can be self-healing, Oral rehydration therapy, and IV fluids \n Medications : Antibiotics and Dietary supplement \n Specialists : Primary Care Provider (PCP), Gastroenterologist, Paediatrician, and Emergency Medicine Doctor", " Ease back into eating. Try to eat small amounts of food frequently if you experience nausea. Otherwise, gradually begin to eat bland, easy-to-digest foods, such as soda crackers, toast, gelatin, bananas, rice and chicken. Stop eating if your nausea returns."],
            'Hepatitis E': [" A liver disease caused by the hepatitis E virus. ", " Treatment consists of self care and fluids \n Hepatitis E usually resolves on its own within four to six weeks. Treatment focuses on supportive care, rehydration and rest. \n Supportive care Can be self-healing and Rehydration \n Self-care Rest and Avoid alcohol \n Specialists Infectious Disease Doctor, Hepatologist, Gastroenterologist, and Primary Care Provider (PCP)", " Regular low calorie meals containing protein (such as meat, fish or beans), starch (such as bread, potatoes or rice) and vitamins (in fruit and vegetables) is the best approach. If you have hepatitis E, and are experiencing symptoms, you should try to take gentle exercise such as a regular walk or a gentle swim."],
            'Drug Reaction': ["  An injury caused by taking a specific medication or some side effects of certain drugs ", " discontinue the medication. ", " no specification. "],
            'Pneumonia': ["Infection that inflames air sacs in one or both lungs, which may fill with fluid.", " Antibiotics can treat many forms of pneumonia. Some forms of pneumonia can be prevented by vaccines. \n Medications Antibiotics and Penicillin antibiotic \n Supportive care : Oxygen therapy, Oral rehydration therapy, and IV fluids \n  Specialists :Infectious Disease Doctor, Lung Specialist, Primary Care Provider (PCP), and Respiratory Therapist", " 1 Water. Water helps to flush out waste products and moisten the tissues along your respiratory tract. ... \n  2 Citrus fruits. Eat two servings of these types of fruit daily: oranges, berries, kiwi fruit and papaya. ... \n  3 Leafy green vegetables. \n 4 Oily fish. \n 5 Probiotics."],
            'GERD': ["Gastroesophageal reflux disease, or GERD, is a digestive disorder that affects the lower esophageal sphincter (LES), the ring of muscle between the esophagus and stomach . ", "If you don’t control your heartburn, it could damage your esophagus and even lead to cancer. There are some simple ways to make sure this doesn’t happen to you. You may be able to manage heartburn symptoms by adjusting your eating, sleeping, and lifestyle habits.Non-prescription antacids and acid reducers may help relieve your heartburn symptoms.Heartburn or GERD that occurs more than twice a week usually responds best to heartburn medicine that you take daily rather than just when you feel symptoms.When medication and lifestyle changes don't work, surgery may be an option. ", " Certain foods can trigger it, but they're not the same for everyone. So when it comes to eating you need to find out what food suits you . food like Vegetables , Ginger , Oatmeal, Noncitrus fruits ,Egg whites , Lean meats, such as chicken, turkey, fish, and seafood, are low-fat and reduce symptoms of acid reflux. "],
            'Chronic cholestasis': [" the sudden inflammation of your gallbladder. If this condition persists over time, such as for months, with repeated attacks, or if there are recurrent problems with gallbladder function, it's known as chronic cholecystitis. ... Gallstones blocking the CBD are the leading cause of cholecystitis.", "Treatment consists of skin care , Treatment aims to remove scales and stop skin cells from growing so quickly. Topical ointments, light therapy and medication can offer relief.Medical procedure Photodynamic therapy . Medications Steroid, Vitamin A derivative, Anti-Inflammatory, Immunosuppressive drug, and Vitamin Self-care Stress management, Petroleum jelly, Coal tar extract, Light therapy, Ultraviolet light therapy, Moisturizer, and Urea Specialists Rheumatologist, Primary Care Provider (PCP), and Dermatologist ", " Fish and seafood. Omega-3 fatty acids—abundant in fatty fish such as salmon, mackerel, sardines, and albacore tuna—are the foundation of a heart-healthy diet. Fish oils are thought to reduce inflammation and help the immune system, which is overactive in people with psoriasis."],
            'Arthritis': [" Inflammation of one or more joints, causing pain and stiffness that can worsen with age. ", " Treatment consists of self care and therapy \n Medication, physiotherapy or sometimes surgery helps reduce symptoms and improve quality of life. \n Self-care : Heating pad, Physical exercise, Weight loss, Yoga, Cold compress, and Ice packs Therapies Hydrotherapy, Stretching, Massage, and Acupuncture \n Surgery : Hip replacement, Knee replacement, and Joint replacement \n Medications : Nonsteroidal anti-Inflammatory drug, Steroid, Analgesic, Narcotic, and Immunosuppressive drug \n Specialists: Primary Care Provider (PCP), Orthopaedic Surgeon, Rheumatologist, and Physiotherapist ", " An Anti-Inflammatory Diet for Arthritis. ... No matter what it is labeled, an anti-inflammatory diet discourages eating processed foods and encourages eating vegetables, fruits, beans, whole grains, and foods containing omega-3 fatty acids, such as wild salmon and anchovies canned in oil. "],
            'Hypertension': [" Hypertension is another name for high blood pressure. It can lead to severe complications and increases the risk of heart disease, stroke, and death. Hypertension and heart disease are global health concerns. The World Health Organization (WHO) suggests that the growth of the processed food industry has impacted the amount of salt in diets worldwide, and that this plays a role in hypertension. ", "  While blood pressure is best regulated through the diet before it reaches the stage of hypertension, there is a range of treatment options. 1 . Regular physical exercise ( for about 30 min a day ) , \n 2 . Stress reduction ( Yoga , Meditation would help) \n 3 . Medications are available , Eventually, a combination of at least two antihypertensive drugs is usually required. \n A range of drug types are available to help lower blood pressure, including: \n 1 . diuretics, including thiazides, chlorthalidone, and indapamide \n 2 . beta-blockers and alpha-blockers \n 3 . calcium-channel blockers \n 4 . central agonists \n 5 . peripheral adrenergic inhibitor \n 6  .vasodilators \n 7 . angiotensin-converting enzyme (ACE) inhibitors \n 8 . angiotensin receptor blockers", " Reducing the amount of salt , Average salt intake is between 9 grams (g) and 12 g per day in most countries around the world. but the recommended salt content by WHO is 5gm , Moderating alcohol consumption , Eating more fruit and vegetables and less fat , Managing body weight"],
            'Common Cold': [" A common viral infection of the nose and throat. ", "Treatment consists of anti-inflammatories and decongestants most people recover on their own within two weeks. Over-the-counter products and home remedies can help control symptoms. ", " Eat nutritious foods, including fruits and vegetables; Consume foods which boost the immune system; Eat foods which may help relieve cold and flu symptoms like congestion; and. Consume soft foods which are easier to swallow with a sore throat"],
            'Tuberculosis': ["A potentially serious infectious bacterial disease that mainly affects the lungs.", "Treatment isn't always required for those without symptoms. Patients with active symptoms will require a long course of treatment involving multiple antibiotics.", "you need to eat a diet containing a variety of healthy foods, such as: Leafy, dark-colored greens like kale and spinach, for their high iron and B-vitamin content "],
            'Acne': ["A skin condition that occurs when hair follicles plug with oil and dead skin cells.", " Treatments include over-the-counter creams and cleanser, as well as prescription antibiotics", "fresh fruits and salads."],
            'Malaria': ["A disease caused by a plasmodium parasite, transmitted by the bite of infected mosquitoes.", "Fresh juice extracted from sweet lime can be an effective home remedy for malaria. The juice is easy to digest and also have Vitamin C. Apple cider vinegar can help in reducing fever caused in malaria.Dilute apple cider vinegar with water and soak cloth in it.", "High fibre foods like whole grain cereals must be avoided by malaria patients. Instead, the intake of fruits and pulses should be increased as they provide adequate nutrition. Eating fried and processed foods, junk oily and spicy foods can aggravate nausea and can disturb the digestion process in the body"],
            'Hyperthyroidism': [": Hyperthyroidism is a condition of the thyroid. The thyroid is a small, butterfly-shaped gland located at the front of your neck. It produces tetraiodothyronine (T4) and triiodothyronine (T3), which are two primary hormones that control how your cells use energy. Your thyroid gland regulates your metabolism through the release of these hormones.Hyperthyroidism occurs when the thyroid makes too much T4, T3, or both. Diagnosis of overactive thyroid and treatment of the underlying cause can relieve symptoms and prevent complications.", "Antithyroid medications, such as methimazole (Tapazole), stop the thyroid from making hormones. They are a common treatment. Radioactive iodine is given to over 70 percent of U.S. adults with hyperthyroidism, according to the American Thyroid Association. It effectively destroys the cells that produce hormones. Common side effects include dry mouth, dry eyes, sore throat, and changes in taste . Surgery is the only alternate if above things dont work out", "Low-iodine foods ( coffee , egg whites , oats , potatoes , honey), Cruciferous vegetables (bamboo shoots , bok choy , broccoli , cauliflower , mustard) , Vitamins and minerals , Healthy fats (flaxseed oil , olive oil , coconut oil , sunflower oil , safflower oil) , Spices ( green chillies , turmeric , black pepper )"],
            'hepatitis A': ["A highly contagious liver infection caused by the hepatitis A virus.", ": Drinking plenty of fluids is important to prevent dehydration if vomiting occurs. Avoid alcoholand use medications with care. Your liver may have difficulty processing medications and alcohol. ", "That diet should include: Plenty of fruits and vegetables. Whole grains such as oats, brown rice, barley, and quinoa. Lean protein such as fish, skinless chicken, egg whites, and beans."],
            'Hepatitis C': [": An infection caused by a virus that attacks the liver and leads to inflammation.", "New medications are turning hepatitis C into hepatitis cured.", ": Eat vegetables — lots of them and in as many colors as possible. Consume fruit and whole grains in moderate amounts. Eat plant-based or lean protein choices, such as egg whites, nonfat yogurt or milk, beans, nuts, fish and poultry."],
            'Bronchial Asthma': [" A condition in which a person's airways become inflamed, narrow and swell and produce extra mucus, which makes it difficult to breathe.", "Garlic has been used as a natural remedy to manage many diseases, because of its anti-inflammatory properties. Since asthma is an inflammatory disease, it would help relieve asthma symptoms.", ": Take in vitamin D. People with more severe asthma may have low vitamin D levels. Milk, eggs and fish such as salmon all contain vitamin D. Even spending a few minutes outdoors in the sun can increase vitamin D levels. Avoid sulfites. Sulfites can trigger asthma symptoms in some cases"],
            'Chicken pox': ["A highly contagious viral infection which causes an itchy, blister-like rash on the skin.", " Preventable by vaccine.", ": Avoid: Spicy Foods. If you've ever cooked extremely spicy foods with a cut on your finger, you know how painful the contact of spice and wound can be. Chicken pox patients are laden with oral sores, which can become very irritated by any spicy dishes.  "],
            'Hepatitis D': ["A serious liver disease caused by infection with the hepatitis D virus.", "You may be given large doses of a medication called interferon for up to 12 months.", "Avoid the following: Saturated fats found in butter, sour cream, and other high-fat dairy foods, fatty cuts of meat, and fried foods."],
            'Varicose veins': ["Gnarled, enlarged veins, most commonly appearing in the legs and feet.", "compression stockings, exercise or procedures to close or remove the veins.", "A high-fiber diet can also help you maintain a healthy weight and prevent varicose veins. Fill up on fiber-rich grains to reach a suggested intake of 21-25 grams per day for women and 30-38 grams per day for men."],
            'Cervical spondylosis': ["A general term for age-related wear and tear of the spinal discs.", "Use a heating pad or a cold pack on your neck to provide pain relief for sore muscles.Exercise regularly to help you recover faster. Wear a soft neck brace or soft collar toget temporary relief. Apple, garlic, ginger and turmeric are also anti-inflammatory.", ": Fish, nuts and oil seeds are rich sources of omega 3 fatty acids and vitamin E acting against inflammation. Apple, garlic, ginger and turmeric are also anti-inflammatory. Avoid red meat, white potato and coffee as it increase acid load in the body .Include fruit juice and veg soup in the routine diet."],
            'Allergy': ["a damaging immune response by the body to a substance, especially a particular food, pollen, fur, or dust, to which it has become hypersensitive", "Quercetin is a favorite of natural healing advocates who believe that it stabilizes the release of histamines and helps to control allergy symptoms. It's naturally found in broccoli, cauliflower, green tea, and citrus fruits.", ":  Onions, peppers, berries, and parsley all have quercetin.Kiwi is a fuzzy fruit rich in vitamin C. It can also cut down on histamines.Pineapple has an enzyme called bromelain.Tuna, salmon, and mackerel have Omega-3 fatty acids and probiotics."],
            'Paralysis (brain hemorrhage)': ["Paralysis is the loss of muscle function in part of your body. It happens when something goes wrong with the way messages pass between your brain and muscles.", "The paste of the whole plants mixed with mustard oil is used as remedy for paralysis.", ": Canned vegetables are almost always too high in sodium for regular inclusion in theHypoKPP diet. Foods which are on high sodium content should not be used. The diet should also be high in potassium. Bananas, orange juice, milk, and potatoes are all high in potassium."],
            'Typhoid': ["Typhoid is a bacterial infection that can lead to a high fever, diarrhea, and vomiting. It can be fatal. It is caused by the bacteria Salmonella typhi. The infection is often passed on through contaminated food and drinking water, and it is more prevalent in places where handwashing is less frequent", "Wash your hands. Frequent hand-washing in hot, soapy water is the best way to control infection. Avoid drinking untreated water. Contaminated drinking water is a particular problem in areas where typhoid fever is endemic. ", "High intake of carbohydrates which are easily digestible like soft rice, porridge and fruit custards. - Sufficient fluids like coconut water, lassi,fruit juices and glucose water. - Soft cooked vegetables, mashed potatoes and fruits like apple, banana and oranges."],
            'Jaundice': ["A medical condition with yellowing of the skin or whites of the eyes,arising from excess of the pigment bilirubin and typically caused by obstruction of the bile duct, by liver disease, or by excessive breakdown of red blood cells.", "Lemon: Lemons have anti inflammatory property which helps in curing jaundice.It unblocks the bile ducts and protects the liver cells from damageand Papaya leaves: Make a papaya leave paste and add honey to it.", " Water and herbal tea are excellent options. Consider adding milk thistle to your routine. You can prepare a fresh tea or eat the seeds as a snack. Opt for fruits like papaya and mango, which are rich in digestive enzymes."],
            'Osteoarthristis': ["A type of arthritis that occurs when flexible tissue at the ends of bones wears down.", "Treatment consists of self care and therapyMedication, physiotherapy and sometimes surgery can help reduce pain and maintain joint movement.Physical exercise, Weight loss, Menthol, and Ice packs", "Omega-3 fatty acids. While some foods increase levels of inflammation in the body, omega-3s actually work to decrease inflammation by suppressing the production of cytokines and enzymes that break down cartilage. Foods with the highest amount of omega-3 fatty acids are: salmon, either wild, fresh or canned"],
            'Hypoglycemia': ["Low blood sugar, the body's main source of energy.", "Consuming high-sugar foods or drinks, such as orange juice or regular fizzy drinks, can treat this condition. Alternatively, medication can be used to raise blood sugar levels. It's also important that a doctor identifies and treats the underlying cause.", ", a person with hypoglycemia should keep their evening meals small. A good dinner choice will include protein and complex carbohydrates. Dinner ideas include: chicken or tofu with brown rice and vegetables."],
            'Hypothyroidism': ["A condition in which the thyroid gland doesn't produce enough thyroid hormone.", "Foods that contain gluten: Bread, pasta, cereals, beer, etc Soy foods: Tofu, tempeh, edamame beans, soy milk, etc.Cruciferous vegetables: Broccoli, kale, spinach, cabbage, etc.Certain fruits: Peaches, pears and strawberries", "Peaches, pears and strawberries,Tofu, tempeh, edamame beans, soy milk,Broccoli, kale, spinach, cabbage,Bread, pasta, cereals and beer"]
            }

# diseases[val] contains the remedies
print(diseases[val])

dic_jsoned = {'disease': val, 'remedy': diseases[val]}

# print(dic_jsoned)

with open('output.json',  'w') as json_file:
    json.dump(dic_jsoned, json_file)
